services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:2
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
      - "8000:8000"
